# tests use the simulator so they can't run in parallel
# see https://gitlab.com/gitlab-org/gitlab/issues/15536 for future support of locks
stages:
  - build1
  - build2
  - build3

build-latest:
  stage: build1
  tags: [mac, x64, xcode]
  script:
    - ./build.sh
    #- ./build.sh --staging -v "~> 1.1.1-rc1"
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?

build-V1.1.1:
  stage: build2
  tags: [mac, x64, xcode]
  script:
    - ./build.sh -v "1.1.1"
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?

build-V1.0.1:
  stage: build3
  tags: [mac, x64, xcode]
  script:
    - ./build.sh -v 1.0.1
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?
