# tests use the simulator so they can't run in parallel
# see https://gitlab.com/gitlab-org/gitlab/issues/15536 for future support of locks
stages:
  - step1
  - step2
  - step3

test-latest:
  stage: step1
  tags: [mac, x64, xcode]
  script:
    - ./test.sh
    - ./test.sh --clean --carthage -v 1.3.0-rc --staging
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?

test-V1.2.0:
  stage: step2
  tags: [mac, x64, xcode]
  script:
    - ./test.sh -v 1.2.0
    - ./test.sh --clean -v 1.2.0 --carthage
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?

test-V1.1.1:
  stage: step3
  tags: [mac, x64, xcode]
  script:
    - ./test.sh -v "1.1.1" --skip IntTestiOSRegular # Requires 1.2
    - ./test.sh --clean --carthage -v "1.1.1" --skip IntTestiOSRegular # Requires 1.2
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?
