# tests use the simulator so they can't run in parallel
# see https://gitlab.com/gitlab-org/gitlab/issues/15536 for future support of locks
stages:
  - step1
  - step2
  - step3

test-latest:
  stage: step1
  tags: [mac, x64, xcode]
  script:
    - ./test.sh
    - ./test.sh --clean -v 1.3.1
    - ./test.sh --clean --carthage-bin
    - ./test.sh --clean --carthage-bin -v 1.3.1
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?

test-V1.3.0:
  stage: step2
  tags: [mac, x64, xcode]
  script:
    - ./test.sh -v 1.3.0 --skip IntTestiOSRegular # Requires 1.3.1
    - ./test.sh --clean -v 1.3.0 --carthage-bin --skip IntTestiOSRegular # Requires 1.3.1
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?

test-V1.2.0:
  stage: step2
  tags: [mac, x64, xcode]
  script:
    - ./test.sh -v 1.2.0 --skip IntTestiOSRegular # Requires 1.3.1
    - ./test.sh --clean -v 1.2.0 --carthage-bin --skip IntTestiOSRegular # Requires 1.3.1
  retry: 2 # Does it help with "Failed to initiate service connection to simulator"?
