stages:
  - build

  
build:
  stage: build
  tags: [mac, x64, xcode]
  script:
    - for project in ./*/ ; do (cd "${project}" && xcodebuild clean build -project "${project}".xcodeproj -scheme "${project}"); done

