stages:
  - build

  
build:
  stage: build
  tags: [mac, x64, xcode]
  script:
    - project=IntTestiOSEmpty
    - cd ${project}
    - xcodebuild clean -project ${project}.xcodeproj -scheme ${project} 
    - # xcodebuild test -project ${project}.xcodeproj -scheme ${project} -destination 'platform=OS X,arch=x86_64'

