# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
version: 2.1

.build: &build
  steps:
    - checkout
    - run:
        name: Test CocoaPods
        command: ./test.sh #--staging -v "~> 1.1.1-rc2"
    - run:
        name: Test Carthage
        command: ./test.sh --clean --carthage
    - run:
        command: |
          mkdir -p /tmp/test-results
          find . -name *.xcresult -exec cp -r {} /tmp/test-results \;
        when: on_fail
    - store_artifacts:
        path: /tmp/test-results

jobs:
  # https://discuss.circleci.com/t/xcode-11-3-image-released/33757
  xcode-11_3_0-macos-10_15:
    macos: {xcode: "11.3.0"}
    <<: *build

  xcode-11_2_1-macos-10_15:
    macos: {xcode: "11.2.1"}
    <<: *build

  xcode-11_1_0-macos-10_14:
    macos: {xcode: "11.1.0"}
    <<: *build
# Not so important: save some CI credits...
#  xcode-11_0_0-macos-10_14:
#    macos: {xcode: "11.0.0"}
#    <<: *build
  # xcode "10.3.0" and older do not support Swift 5.1

workflows:
  build:
    jobs:
      - xcode-11_3_0-macos-10_15
      - xcode-11_2_1-macos-10_15
      - xcode-11_1_0-macos-10_14
#      - xcode-11_0_0-macos-10_14