# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
version: 2.1

build_tpl: &build
  steps:
    - checkout
    - run:
        name: Install realpath & co.
        command: brew install coreutils
    - run:
        name: Build all the tests
        command: bash -x build.sh

jobs:
  xcode-11_2_1-macos-10_15:
    macos:
      xcode: "11_2_1"
    <<: *build
  xcode-11_1_0-macos-10_14:
    macos:
      xcode: "11_1_0"
    <<: *build
  xcode-10_3_0-macos-10_14:
    macos:
      xcode: "10_3_0"
    <<: *build