# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
version: 2.1

# Framework compiled with Swift 5.2 seems incompatible to Swift 5.1 compiler:
# results in "error: unknown attribute '_hasMissingDesignatedInitializers'"; see also:
# https://forums.swift.org/t/cant-use-framework-compiled-with-swift-5-2-in-swift-5-1-3-project/35248
.build52: &swift5_2
  steps:
    - checkout
    - run:
        name: Test CocoaPods rc
        command: ./test.sh --clean --staging -v "1.4.0-RC"
    - run:
        name: Test CocoaPods latest
        command: ./test.sh --clean
    - run:
        name: Test CocoaPods latest explicit version
        command: ./test.sh --clean -v "1.3.1"
    - run:
        name: Update Carthage
        command: brew update && brew upgrade carthage
    - run:
        name: Test Carthage rc
        command: ./test.sh --clean --staging --carthage-bin -v 1.4.0-rc
    - run:
        name: Test Carthage latest
        command: ./test.sh --clean --carthage-bin
    - run:
        name: Test Carthage latest explicit version
        command: ./test.sh --clean --carthage-bin -v 1.3.1
    - run:
        command: |
          mkdir -p /tmp/test-results
          find . -name *.xcresult -exec cp -r {} /tmp/test-results \;
        when: on_fail
    - store_artifacts:
        path: /tmp/test-results

# Swift 5.2 was introduced in Xcode 11.4

jobs:
  xcode-12_0_0-macos-10_15:
    macos: {xcode: "12.0.0"} # beta 6 as of 2020/09
    <<: *swift5_2

  xcode-11_7_0-macos-10_15:
    macos: {xcode: "11.7.0"}
    <<: *swift5_2

  xcode-11_6_0-macos-10_15:
    macos: {xcode: "11.6.0"}
    <<: *swift5_2

  xcode-11_5_0-macos-10_15:
    macos: {xcode: "11.5.0"}
    <<: *swift5_2

  xcode-11_4_1-macos-10_15:
    macos: {xcode: "11.4.1"}
    <<: *swift5_2

  xcode-11_4_0-macos-10_15:
    macos: {xcode: "11.4.0"}
    <<: *swift5_2

workflows:
  build:
    jobs:
      - xcode-12_0_0-macos-10_15
      - xcode-11_7_0-macos-10_15
      - xcode-11_6_0-macos-10_15
      - xcode-11_5_0-macos-10_15
      - xcode-11_4_1-macos-10_15
      - xcode-11_4_0-macos-10_15
