# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
version: 2.1

# Framework compiled with Swift 5.2 seems incompatible to Swift 5.1 compiler:
# results in "error: unknown attribute '_hasMissingDesignatedInitializers'"; see also:
# https://forums.swift.org/t/cant-use-framework-compiled-with-swift-5-2-in-swift-5-1-3-project/35248
.build52: &swift5_2
  steps:
    - checkout
    - run:
        name: Test CocoaPods latest
        command: ./test.sh
    - run:
        name: Test CocoaPods latest explicit version
        command: ./test.sh --clean -v "1.3.1"
    - run:
        name: Test Carthage latest
        command: ./test.sh --clean --carthage-bin
    - run:
        name: Test Carthage latest explicit version
        command: ./test.sh --clean --carthage-bin -v 1.3.1
    - run:
        command: |
          mkdir -p /tmp/test-results
          find . -name *.xcresult -exec cp -r {} /tmp/test-results \;
        when: on_fail
    - store_artifacts:
        path: /tmp/test-results

.build51: &swift5_1
  steps:
    - checkout
    - run:
        name: Test CocoaPods
        command: ./test.sh -v "1.2.0"
    - run:
        name: Test Carthage
        command: ./test.sh --clean --carthage-bin -v 1.2.0
    - run:
        command: |
          mkdir -p /tmp/test-results
          find . -name *.xcresult -exec cp -r {} /tmp/test-results \;
        when: on_fail
    - store_artifacts:
        path: /tmp/test-results

jobs:
  xcode-11_5_0-macos-10_15:
    macos: {xcode: "11.5.0"}
    <<: *swift5_2

  xcode-11_4_1-macos-10_15:
    macos: {xcode: "11.4.1"}
    <<: *swift5_2

  xcode-11_4_0-macos-10_15:
    macos: {xcode: "11.4.0"}
    <<: *swift5_2

#  xcode-11_3_1-macos-10_15:
#    macos: {xcode: "11.3.1"}
#    <<: *swift5_1
#
#  # https://discuss.circleci.com/t/xcode-11-3-image-released/33757
#  xcode-11_3_0-macos-10_15:
#    macos: {xcode: "11.3.0"}
#    <<: *swift5_1
#
#  xcode-11_2_1-macos-10_15:
#    macos: {xcode: "11.2.1"}
#    <<: *swift5_1
#
#  xcode-11_1_0-macos-10_14:
#    macos: {xcode: "11.1.0"}
#    <<: *swift5_1
# Not so important: save some CI credits...
#  xcode-11_0_0-macos-10_14:
#    macos: {xcode: "11.0.0"}
#    <<: *build
  # xcode "10.3.0" and older do not support Swift 5.1

workflows:
  build:
    jobs:
      - xcode-11_5_0-macos-10_15
      - xcode-11_4_1-macos-10_15
      - xcode-11_4_0-macos-10_15
#      - xcode-11_3_1-macos-10_15
#      - xcode-11_3_0-macos-10_15
#      - xcode-11_2_1-macos-10_15
#      - xcode-11_1_0-macos-10_14
#      - xcode-11_0_0-macos-10_14